package cn.cellcom.szba.vo;

import java.util.ArrayList;
import java.util.List;

/**
 * TUrl generated by MyEclipse Persistence Tools
 */

public class SqlAndParamVO implements java.io.Serializable {

	// Fields

	private String sql;

	private List param = new ArrayList();

	public List getParam() {
		return param;
	}

	public void setParam(List param) {
		this.param = param;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	
}