package cn.cellcom.wechat.po;

import java.util.Date;

import org.apache.commons.lang.StringUtils;


import cn.cellcom.common.date.DateTool;
import cn.cellcom.wechat.common.Env;

/**
 * AbstractTCallforward generated by MyEclipse Persistence Tools
 */

public class TCallforward implements java.io.Serializable {

	// Fields

	private Long id;

	private String regNo;

	private String cfType;

	private String cfNumber;

	private Long seqid;

	private Date submitTime;

	private String handleStatus;

	private Date operateTime;

	private String operateType;

	private String handleDesc;

	private String operator;

	private String result;

	// Constructors

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getHandleDesc() {
		return handleDesc;
	}

	public void setHandleDesc(String handleDesc) {
		this.handleDesc = handleDesc;
	}

	/** default constructor */
	public TCallforward() {
	}

	/** full constructor */
	public TCallforward(String regNo, String cfType, String cfNumber,
			Long seqid, Date submitTime, String handleStatus, Date operateTime,
			String operateType) {
		this.regNo = regNo;
		this.cfType = cfType;
		this.cfNumber = cfNumber;
		this.seqid = seqid;
		this.submitTime = submitTime;
		this.handleStatus = handleStatus;
		this.operateTime = operateTime;
		this.operateType = operateType;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	public String getCfType() {
		return this.cfType;
	}

	public void setCfType(String cfType) {
		this.cfType = cfType;
	}

	public String getCfNumber() {
		return this.cfNumber;
	}

	public void setCfNumber(String cfNumber) {
		this.cfNumber = cfNumber;
	}

	public Long getSeqid() {
		return this.seqid;
	}

	public void setSeqid(Long seqid) {
		this.seqid = seqid;
	}

	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public String getHandleStatus() {
		return this.handleStatus;
	}

	public void setHandleStatus(String handleStatus) {
		this.handleStatus = handleStatus;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getOperateType() {
		return this.operateType;
	}

	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	public String getDiffSubmitTimeStr() {
		if (this.submitTime != null) {
			return DateTool.Diff(this.submitTime, new Date());
		}
		return null;
	}
	public String getCfTypeStr(){
		if(StringUtils.isNotBlank(this.cfType)){
			return Env.CALLFORWARD_TYPE.get(this.cfType);
		}
		return null;
	}
	
	public String getHandleStatusStr(){
		if(StringUtils.isNotBlank(this.handleStatus)){
			return Env.CALLFORWARD_STATUS.get(this.handleStatus);
		}
		return null;
	}

}