package cn.cellcom.wechat.po;

/**
 * TMobileHead generated by MyEclipse Persistence Tools
 */

public class TMobileHead implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String headnum;

	private String headzone;

	// Constructors

	/** default constructor */
	public TMobileHead() {
	}

	/** full constructor */
	public TMobileHead(String headnum, String headzone) {
		this.headnum = headnum;
		this.headzone = headzone;
	}

	// Property accessors

	public String getHeadnum() {
		return this.headnum;
	}

	public void setHeadnum(String headnum) {
		this.headnum = headnum;
	}

	public String getHeadzone() {
		return this.headzone;
	}

	public void setHeadzone(String headzone) {
		this.headzone = headzone;
	}

}