package cn.cellcom.szba.domain;

/**
 * TUrlGroup generated by MyEclipse Persistence Tools
 */

public class TUrlGroup implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String description;

	private String createTime;

	// Constructors

	/** default constructor */
	public TUrlGroup() {
	}

	/** minimal constructor */
	public TUrlGroup(String name) {
		this.name = name;
	}

	/** full constructor */
	public TUrlGroup(String name, String description, String createTime) {
		this.name = name;
		this.description = description;
		this.createTime = createTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}