package cn.cellcom.esb.po;

import java.util.Date;



/**
 * TOperateLog generated by MyEclipse - Hibernate Tools
 */

public class TOperateCrmLog implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;

	private String operator;

	private String ip;

	private String operateDesc;

	private Date operateTime;

	private String operateType;

	private String platform;

	private String regNo;

	// Constructors

	/** default constructor */
	public TOperateCrmLog() {
	}

	/** full constructor */
	public TOperateCrmLog(String operator, String ip, String operateDesc,
			Date operateTime, String operateType, String platform,String operateTable,
			String regNo) {
		this.operator = operator;
		this.ip = ip;
		this.operateDesc = operateDesc;
		this.operateTime = operateTime;
		this.operateType = operateType;
		this.platform  = platform;
		this.regNo = regNo;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getOperateDesc() {
		return this.operateDesc;
	}

	public void setOperateDesc(String operateDesc) {
		this.operateDesc = operateDesc;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getOperateType() {
		return this.operateType;
	}

	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	

	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getPartDesc() {
		if (this.operateDesc == null) {
			return "";
		} else if (this.operateDesc.length() > 72) {
			return new String(this.operateDesc.substring(0, 72));
		} else {
			return this.operateDesc;
		}
	}

	/**
	 * 
	 * @return the regNo
	 */
	public String getRegNo() {
		return regNo;
	}

	/**
	 * 
	 * @param regNo
	 *            the regNo to set
	 */
	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

}